package com.amnlak.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.NumberFormat;import java.util.*;

public class MainActivity extends Activity{
 int navy=Color.rgb(8,24,43), gold=Color.rgb(220,174,70), bg=Color.rgb(246,248,251), ink=Color.rgb(19,37,58); LinearLayout root,content; NumberFormat nf=NumberFormat.getInstance(new Locale("fa","IR"));
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(navy);home();}
 TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(18,8,18,8);return t;}
 GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackground(shape(gold,18));return b;}
 EditText input(String s){EditText e=new EditText(this);e.setHint(s);e.setTextSize(16);e.setGravity(Gravity.RIGHT);e.setInputType(2|8192);e.setBackground(shape(Color.WHITE,16));e.setPadding(16,0,16,0);e.setLayoutParams(new LinearLayout.LayoutParams(-1,58));return e;}
 void frame(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(10,10,10,10);bar.setBackgroundColor(navy);TextView menu=tv("☰",30,Color.WHITE);menu.setGravity(Gravity.CENTER);menu.setOnClickListener(v->drawer());bar.addView(menu,new LinearLayout.LayoutParams(58,58));TextView brand=tv(title+"  |  Amnlak",20,Color.WHITE);brand.setTypeface(null,1);bar.addView(brand,new LinearLayout.LayoutParams(0,58,1));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.amnlak_logo);bar.addView(logo,new LinearLayout.LayoutParams(48,48));root.addView(bar);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,16,18,24);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 void drawer(){final PopupWindow p=new PopupWindow(this);LinearLayout d=new LinearLayout(this);d.setOrientation(LinearLayout.VERTICAL);d.setPadding(18,30,18,18);d.setBackgroundColor(navy);TextView h=tv("امنلاک",25,Color.WHITE);h.setTypeface(null,1);d.addView(h);d.addView(tv("ابزار هوشمند ملک و ساخت",14,0xffb7c4d1));String[] items={"خانه","کمیسیون املاک","مشارکت در ساخت","محاسبات مهندسی","اطلاعات توسعه‌دهنده"};for(String x:items){TextView i=tv("›  "+x,17,Color.WHITE);i.setPadding(16,20,16,20);d.addView(i);i.setOnClickListener(v->{p.dismiss();if(x.equals("خانه"))home();else if(x.startsWith("کمیسیون"))commission();else if(x.startsWith("مشارکت"))partnership();else if(x.startsWith("محاسبات"))engineering();else developer();});}p.setContentView(d);p.setWidth(300);p.setHeight(-1);p.setBackgroundDrawable(shape(navy,0));p.setOutsideTouchable(true);p.setFocusable(true);p.showAtLocation(root,Gravity.RIGHT|Gravity.TOP,0,0);}
 void home(){frame("خانه");content.addView(tv("سلام، خوش آمدید 👋",25,ink));content.addView(tv("محاسبات دقیق برای تصمیم‌های بهتر در ملک و ساخت‌وساز",15,0xff607080));card("کمیسیون املاک","رهن، اجاره، خرید و فروش",v->commission());card("مشارکت در ساخت","سهم مالک، سازنده و سود پروژه",v->partnership());card("محاسبات مهندسی","زیربنا، میلگرد و بتن",v->engineering());TextView tip=tv("نسخه ۱.۰.۰  •  طراحی مدرن امنلاک",13,0xff718092);tip.setGravity(Gravity.CENTER);content.addView(tip,new LinearLayout.LayoutParams(-1,65));}
 void card(String a,String b,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,10,18,10);c.setBackground(shape(Color.WHITE,22));TextView x=tv(a,19,ink);x.setTypeface(null,1);c.addView(x);c.addView(tv(b,14,0xff6c7a89));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,92);p.setMargins(0,9,0,5);content.addView(c,p);}
 void pageTitle(String s){content.addView(tv(s,24,ink));content.addView(tv("مقادیر را وارد کنید و نتیجه را دریافت کنید",14,0xff68798a));}
 double val(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",",""));}catch(Exception x){return 0;}}
 void out(TextView t,String s){t.setText(s);t.setTextSize(18);t.setTextColor(navy);t.setTypeface(null,1);t.setPadding(18,18,18,18);t.setBackground(shape(0xffe9f1f6,18));}
 void commission(){frame("کمیسیون");pageTitle("محاسبه کمیسیون املاک");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"خرید و فروش","رهن کامل","اجاره"}));content.addView(sp);EditText a=input("مبلغ معامله یا رهن (تومان)"),r=input("اجاره ماهانه (برای اجاره)");content.addView(a);content.addView(r);CheckBox tax=new CheckBox(this);tax.setText("افزودن ۹٪ مالیات ارزش افزوده");tax.setChecked(true);content.addView(tax);Button b=btn("محاسبه");content.addView(b);TextView o=tv("نتیجه محاسبه",16,ink);content.addView(o);b.setOnClickListener(v->{double x=sp.getSelectedItemPosition()==0?val(a)*.0025:sp.getSelectedItemPosition()==1?val(a)*.005:val(r)*.25;out(o,"سهم هر طرف: "+nf.format(x)+" تومان\nبا مالیات: "+nf.format(x*(tax.isChecked()?1.09:1))+" تومان");});}
 void partnership(){frame("مشارکت");pageTitle("مشارکت در ساخت");EditText l=input("ارزش زمین (تومان)"),c=input("هزینه ساخت کل (تومان)"),f=input("ارزش نهایی پروژه (تومان)");content.addView(l);content.addView(c);content.addView(f);Button b=btn("محاسبه سهم و سود");content.addView(b);TextView o=tv("نتیجه محاسبه",16,ink);content.addView(o);b.setOnClickListener(v->{double a=val(l),x=val(c),z=val(f),sum=a+x;out(o,"سهم مالک: "+nf.format(a/sum*100)+"٪\nسهم سازنده: "+nf.format(x/sum*100)+"٪\nسود کل: "+nf.format(z-sum)+" تومان");});}
 void engineering(){frame("مهندسی");pageTitle("محاسبات مهندسی ساختمان");EditText a=input("مساحت هر طبقه (مترمربع)"),f=input("تعداد طبقات"),s=input("میلگرد (کیلوگرم بر مترمربع)");content.addView(a);content.addView(f);content.addView(s);Button b=btn("محاسبه برآورد");content.addView(b);TextView o=tv("نتیجه محاسبه",16,ink);content.addView(o);b.setOnClickListener(v->{double x=val(a)*val(f);out(o,"زیربنای کل: "+nf.format(x)+" مترمربع\nمیلگرد تقریبی: "+nf.format(x*val(s))+" کیلوگرم\nبتن تقریبی: "+nf.format(x*.35)+" مترمکعب");});}
 void developer(){frame("توسعه‌دهنده");pageTitle("اطلاعات توسعه‌دهنده");content.addView(tv("این اپلیکیشن برای توسعه مداوم طراحی شده است.",16,ink));TextView phone=tv("📞  ۰۹۱۲۷۲۸۵۰۶۵\n\n📱  Instagram   @amnlak\n💬  Telegram    @amnlak\n🌐  GitHub       github.com/amnlak",18,ink);phone.setBackground(shape(Color.WHITE,20));content.addView(phone,new LinearLayout.LayoutParams(-1,190));Button call=btn("تماس با توسعه‌دهنده");content.addView(call);call.setOnClickListener(v->{startActivity(new Intent(Intent.ACTION_DIAL, Uri.parse("tel:09127285065")));});}
}
